config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :pays
  resources :mains
  resources :status_slots
  resources :registers
  resources :searches
  resources :inventories
  resources :products
  resources :orders
  resources :materials

  

  
  namespace :admin do
    devise_for :admins
    # các route của admin
    
  end
  resources :items 
  mount RailsAdmin::Engine => '/dashboard,admin', as: 'rails_admin'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :orders do
    get 'printbill', on: :member
  end

 # config/routes.rb

  Rails.application.routes.draw do
  resources :pays
  resources :mains
  resources :status_slots
  resources :registers
  resources :searches
    get 'dashboard/index'
    # Other routes
  end



  devise_for :users
  match '/404', to: 'errors#not_found', via: :all
  root to: 'home#home1'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "dashboard#index", as: "dashboard"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory.rb
class Inventory < ApplicationRecord
      validates_presence_of :name , :quantity , :import_day , :exp_day , :provider 
      validates_uniqueness_of :name
end

app/models/main.rb
class Main < ApplicationRecord
    
        has_one :pay, foreign_key: 'car_plate', primary_key: 'car_plate'
    
      
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :product
    validates_presence_of :name , :quantity 
    validates :phone, presence: true, length: { is: 10 }
    has_one :membership, primary_key: :phone, foreign_key: :phone
    belongs_to :membership, optional: true
    belongs_to :membership, foreign_key: :phone, primary_key: :phone, optional: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    # Your associations and validations for the OrderItem model
  end

app/models/pay.rb
class Pay < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    validates_presence_of :name , :quantity , :price  
    validates_uniqueness_of :name
end

app/models/register.rb
class Register < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/status_slot.rb
class StatusSlot < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/status_slots_controller.rb
class StatusSlotsController < ApplicationController
  before_action :set_status_slot, only: %i[ show edit update destroy ]

  # GET /status_slots or /status_slots.json
  def index
    @status_slots = StatusSlot.all
  end

  # GET /status_slots/1 or /status_slots/1.json
  def show
  end

  # GET /status_slots/new
  def new
    @status_slot = StatusSlot.new
  end

  # GET /status_slots/1/edit
  def edit
  end

  # POST /status_slots or /status_slots.json
  def create
    @status_slot = StatusSlot.new(status_slot_params)

    respond_to do |format|
      if @status_slot.save
        format.html { redirect_to status_slot_url(@status_slot), notice: "Status slot was successfully created." }
        format.json { render :show, status: :created, location: @status_slot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_slots/1 or /status_slots/1.json
  def update
    respond_to do |format|
      if @status_slot.update(status_slot_params)
        format.html { redirect_to status_slot_url(@status_slot), notice: "Status slot was successfully updated." }
        format.json { render :show, status: :ok, location: @status_slot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_slots/1 or /status_slots/1.json
  def destroy
    @status_slot.destroy

    respond_to do |format|
      format.html { redirect_to status_slots_url, notice: "Status slot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_slot
      @status_slot = StatusSlot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_slot_params
      params.require(:status_slot).permit(:vehicle_type, :license_plate, :status, :slots)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pays_helper.rb
module PaysHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/status_slots_helper.rb
module StatusSlotsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/status_slots/_form.html.erb
<%= form_with(model: status_slot) do |form| %>
<% if status_slot.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(status_slot.errors.count, "error") %> prohibited this status_slot from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% status_slot.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :vehicle_type, class: label_class %>
          <%= form.text_field :vehicle_type, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :license_plate, class: label_class %>
          <%= form.text_field :license_plate, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :status, class: label_class %>
          <%= form.check_box :status, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :slots, class: label_class %>
          <%= form.number_field :slots, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if status_slot.persisted? %>
<%= link_to "Cancel", status_slot, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", status_slots_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/status_slots/_status_slot.html.erb
<div id="<%= dom_id status_slot %>">
  <p>
    <strong>Vehicle type:</strong>
    <%= status_slot.vehicle_type %>
  </p>

  <p>
    <strong>License plate:</strong>
    <%= status_slot.license_plate %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= status_slot.status %>
  </p>

  <p>
    <strong>Slots:</strong>
    <%= status_slot.slots %>
  </p>

</div>

app/views/status_slots/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit status_slot</h1>
    <% if @status_slot.persisted? %>
    <%= button_to 'Destroy', @status_slot, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', status_slot: @status_slot %>
</div>

app/views/status_slots/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Status_slots</h1>

    <%= link_to new_status_slot_path, class: button_class(theme: "primary") do %>
    Add New Status slot
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Vehicle type</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">License plate</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Status</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Slots</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @status_slots.each do |status_slot| %>
      <%= content_tag :tr, id: dom_id(status_slot), class: dom_class(status_slot) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= status_slot.vehicle_type %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= status_slot.license_plate %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= status_slot.status %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= status_slot.slots %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', status_slot %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/status_slots/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New status_slot</h1>

  <%= render 'form', status_slot: @status_slot %>
</div>

app/views/status_slots/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Status_slot</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to status_slots_path, class: button_class(theme: "transparent") do %>
      All Status_slots
      <% end %>
      <%= link_to edit_status_slot_path(@status_slot), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Vehicle type:</p>
        <p><%= @status_slot.vehicle_type %></p>
      </li>
      <li>
        <p class="font-semibold">License plate:</p>
        <p><%= @status_slot.license_plate %></p>
      </li>
      <li>
        <p class="font-semibold">Status:</p>
        <p><%= @status_slot.status %></p>
      </li>
      <li>
        <p class="font-semibold">Slots:</p>
        <p><%= @status_slot.slots %></p>
      </li>
  </ul>
</div>