config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :pays
  resources :mains
  resources :status_slots
  resources :registers
  resources :searches
  resources :inventories
  resources :products
  resources :orders
  resources :materials

  

  
  namespace :admin do
    devise_for :admins
    # các route của admin
    
  end
  resources :items 
  mount RailsAdmin::Engine => '/dashboard,admin', as: 'rails_admin'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :orders do
    get 'printbill', on: :member
  end

 # config/routes.rb

  Rails.application.routes.draw do
  resources :pays
  resources :mains
  resources :status_slots
  resources :registers
  resources :searches
    get 'dashboard/index'
    # Other routes
  end



  devise_for :users
  match '/404', to: 'errors#not_found', via: :all
  root to: 'home#home1'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "dashboard#index", as: "dashboard"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory.rb
class Inventory < ApplicationRecord
      validates_presence_of :name , :quantity , :import_day , :exp_day , :provider 
      validates_uniqueness_of :name
end

app/models/main.rb
class Main < ApplicationRecord
    
        has_one :pay, foreign_key: 'car_plate', primary_key: 'car_plate'
    
      
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :product
    validates_presence_of :name , :quantity 
    validates :phone, presence: true, length: { is: 10 }
    has_one :membership, primary_key: :phone, foreign_key: :phone
    belongs_to :membership, optional: true
    belongs_to :membership, foreign_key: :phone, primary_key: :phone, optional: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    # Your associations and validations for the OrderItem model
  end

app/models/pay.rb
class Pay < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    validates_presence_of :name , :quantity , :price  
    validates_uniqueness_of :name
end

app/models/register.rb
class Register < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/status_slot.rb
class StatusSlot < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: %i[ show edit update destroy ]

  # GET /mains or /mains.json
  def index
    @mains = Main.all
  end

  # GET /mains/1 or /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end

  # GET /mains/1/edit
  def edit
  end

  # POST /mains or /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to main_url(@main), notice: "Main was successfully created." }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mains/1 or /mains/1.json
  def update
    respond_to do |format|
      if @main.update(main_params)
        format.html { redirect_to main_url(@main), notice: "Main was successfully updated." }
        format.json { render :show, status: :ok, location: @main }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1 or /mains/1.json
  def destroy
    @main.destroy

    respond_to do |format|
      format.html { redirect_to mains_url, notice: "Main was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main
      @main = Main.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def main_params
      params.require(:main).permit(:car_type, :car_plate, :check_in_time, :phone_number, :parking_slots)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classes(flash_type)
    flash_base = "px-2 py-4 mx-auto font-sans font-medium text-center text-white"
    {
      notice: "bg-indigo-600 #{flash_base}",
      error:  "bg-red-600 #{flash_base}",
      alert: "bg-red-600 #{flash_base}"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def nav_classes
    ["devise/registrations", "devise/sessions", "devise/confirmations", "devise/passwords", "devise/unlocks"].include?(params[:controller]) ? "hidden" : nil
  end

  def label_class(options={})
    "block mb-1 font-normal leading-normal #{options[:extended_classes]}"
  end

  def input_class(options={})
    "rounded border border-gray-300 block w-full focus:outline-none focus:border-gray-400 outline-none focus-within:outline-none focus:ring-2 focus:ring-gray-200 #{options[:extended_classes]}"
  end

  def checkbox_class(options={})
    "rounded border-gray-300 border focus:ring-2 focus:ring-gray-200 text-blue-500 mr-1 #{options[:extended_classes]}"
  end

  def link_class(options={})
    "text-gray-700 underline hover:no-underline hover:text-gray-800 block #{options[:extended_classes]}"
  end

  def button_class(options={})
    variant = options[:variant]
    theme = options[:theme]

    style_button(variant, theme_button(theme))
  end

  def theme_button(theme)
    themes = {
      primary: "primary",
      secondary: "secondary",
      transparent: "transparent",
      dark: "dark"
    }

    case theme
    when themes[:primary]
      "bg-indigo-600 hover:bg-indigo-700 text-white"
    when themes[:secondary]
      "bg-teal-600 hover:bg-teal-700 text-white"
    when themes[:transparent]
      "bg-transparent hover:bg-gray-100 text-gray-700"
    when themes[:dark]
      "bg-gray-800 text-white shadow-sm hover:bg-gray-900"
    else
      "bg-white border border-gray-300 shadow-sm hover:bg-gray-100"
    end
  end

  def style_button(variant, theme)
    base = "rounded text-center font-sans font-normal outline-none leading-normal cursor-pointer transition ease-in-out duration-200 font-medium"

    case variant
    when "large"
      "px-5 py-4 text-lg #{base} #{theme}"
    when "small"
      "py-2 px-4 text-sm #{base} #{theme}"
    when "expanded"
      "p-3 w-full block #{base} #{theme}"
    else
      "px-5 py-2 text-base #{base} #{theme}"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pays_helper.rb
module PaysHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/mains/_form.html.erb
<%= form_with(model: main) do |form| %>
<% if main.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(main.errors.count, "error") %> prohibited this main from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% main.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :car_type, class: label_class %>
          <%= form.text_field :car_type, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :car_plate, class: label_class %>
          <%= form.text_field :car_plate, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :check_in_time, class: label_class %>
          <%= form.datetime_field :check_in_time, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :phone_number, class: label_class %>
          <%= form.text_field :phone_number, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :parking_slots, class: label_class %>
          <%= form.text_field :parking_slots, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if main.persisted? %>
<%= link_to "Cancel", main, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", mains_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/mains/_main.html.erb
<div id="<%= dom_id main %>">
  <p>
    <strong>Car type:</strong>
    <%= main.car_type %>
  </p>

  <p>
    <strong>Car plate:</strong>
    <%= main.car_plate %>
  </p>

  <p>
    <strong>Check in time:</strong>
    <%= main.check_in_time %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= main.phone_number %>
  </p>

  <p>
    <strong>Parking slots:</strong>
    <%= main.parking_slots %>
  </p>

</div>

app/views/mains/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit main</h1>
    <% if @main.persisted? %>
    <%= button_to 'Destroy', @main, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', main: @main %>
</div>

app/views/mains/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Mains</h1>

    <%= link_to new_main_path, class: button_class(theme: "primary") do %>
    Add New Main
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Car type</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Car plate</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Check in time</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Phone number</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Parking slots</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @mains.each do |main| %>
      <%= content_tag :tr, id: dom_id(main), class: dom_class(main) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= main.car_type %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= main.car_plate %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= main.check_in_time %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= main.phone_number %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= main.parking_slots %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', main %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/mains/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New main</h1>

  <%= render 'form', main: @main %>
</div>

app/views/mains/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Main</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to mains_path, class: button_class(theme: "transparent") do %>
      All Mains
      <% end %>
      <%= link_to edit_main_path(@main), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Car type:</p>
        <p><%= @main.car_type %></p>
      </li>
      <li>
        <p class="font-semibold">Car plate:</p>
        <p><%= @main.car_plate %></p>
      </li>
      <li>
        <p class="font-semibold">Check in time:</p>
        <p><%= @main.check_in_time %></p>
      </li>
      <li>
        <p class="font-semibold">Phone number:</p>
        <p><%= @main.phone_number %></p>
      </li>
      <li>
        <p class="font-semibold">Parking slots:</p>
        <p><%= @main.parking_slots %></p>
      </li>
  </ul>
</div>